services:
  gatehouse-mail:
    image: gatehouse-mail:latest
    build: .
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./data:/data
    ports:
      #8081 port exposes the full inbound webhook endpoint, API and web ui
      - "0.0.0.0:8081:8081"
      #8092 port exposes only the inbound webhook endpoint.
      #For more security only expose this port to the internet to receive mail
      - "0.0.0.0:8082:8082"
