//go:build ignore

package main

// Generator for zones_gen.go. It walks the zoneinfo.zip that ships with the Go
// toolchain and writes the sorted list of selectable IANA zone names.
//
// Regenerate with:
//
//	./mailmoose-go.sh generate ./internal/timezone
//
// or, from inside a container:
//
//	cd internal/timezone && go run gen.go
//
// Re-run only when bumping the Go toolchain / IANA database. The generated file
// is committed so the build needs no generator step.

import (
	"archive/zip"
	"fmt"
	"go/format"
	"os"
	"path"
	"runtime"
	"sort"
	"strings"
)

func main() {
	zipPath := path.Join(runtime.GOROOT(), "lib", "time", "zoneinfo.zip")
	zr, err := zip.OpenReader(zipPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "open zoneinfo.zip: %v\n", err)
		os.Exit(1)
	}
	defer zr.Close()

	seen := map[string]bool{}
	var names []string
	for _, f := range zr.File {
		name := f.Name
		// Keep only real zone entries: drop the informational tab files and the
		// posix/ and right/ mirror trees, which duplicate canonical names.
		if strings.HasSuffix(name, ".tab") ||
			strings.HasPrefix(name, "posix/") ||
			strings.HasPrefix(name, "right/") ||
			name == "zone.tab" || name == "zone1970.tab" || name == "iso3166.tab" {
			continue
		}
		if strings.Contains(name, "..") || strings.HasPrefix(name, "/") {
			continue
		}
		if seen[name] {
			continue
		}
		seen[name] = true
		names = append(names, name)
	}
	sort.Strings(names)

	var b strings.Builder
	b.WriteString("// Code generated by gen.go; DO NOT EDIT.\n\n")
	b.WriteString("package timezone\n\n")
	b.WriteString("// IANAZones is the sorted list of IANA time zone names selectable in the UI.\n")
	b.WriteString("var IANAZones = []string{\n")
	for _, n := range names {
		fmt.Fprintf(&b, "\t%q,\n", n)
	}
	b.WriteString("}\n")

	src, err := format.Source([]byte(b.String()))
	if err != nil {
		fmt.Fprintf(os.Stderr, "format: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile("zones_gen.go", src, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write: %v\n", err)
		os.Exit(1)
	}
	fmt.Fprintf(os.Stderr, "wrote zones_gen.go with %d zones\n", len(names))
}
