package app

import (
	"fmt"
	"html"
	"net/url"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"time"

	"gatehouse-mail/internal/mailparse"
	"gatehouse-mail/internal/model"
	"gatehouse-mail/internal/transport"
)

// workflowTokenRe matches any approval control token marker (request reference
// or decision subject) so the dead token can be redacted from a retained
// workflow copy once the request is terminal.
var workflowTokenRe = regexp.MustCompile(`\[GH-(REQUEST|APPROVE|REJECT):[A-Za-z0-9_-]+\]`)

// redactWorkflowTokens replaces every control token marker with a redacted
// placeholder. The token is dead once the request is terminal, but removing it
// from the retained copy is cheap defense-in-depth.
func redactWorkflowTokens(s string) string {
	return workflowTokenRe.ReplaceAllString(s, "[GH-$1:REDACTED]")
}

// controlSubjectPrefixes are the strict subjects an approval control email must
// contain. They are parsed by the inbound control handler.
const (
	controlApprove = "APPROVE"
	controlReject  = "REJECT"
	controlRequest = "REQUEST"
	feedbackBegin  = "[GH-FEEDBACK-BEGIN]"
	feedbackEnd    = "[GH-FEEDBACK-END]"
)

// controlRequestMarker is the reference line embedded in an approval-request
// email. It is quoted back by a plain reply so the reply can be linked to its
// draft without relying on the mailto buttons, which some webmail clients
// (notably Outlook on the web) do not open. The token is the same one the
// buttons carry; only its SHA-256 hash is stored.
func controlRequestMarker(token string) string {
	return "[GH-" + controlRequest + ":" + token + "]"
}

// approvalEmailSubject is the human-readable subject of the approval-request
// email. The control token travels in the reply subject generated by the
// buttons, not here.
func approvalEmailSubject(draftSubject string) string {
	draftSubject = strings.TrimSpace(draftSubject)
	if draftSubject == "" {
		draftSubject = "(no subject)"
	}
	return "Approval required: " + draftSubject
}

// controlBody is the pre-filled reply body containing the feedback markers.
func controlBody() string {
	return feedbackBegin + "\r\n\r\n\r\n" + feedbackEnd + "\r\n"
}

// controlReplySubject is the subject an approver's reply must carry: the strict
// control token followed by the draft subject, so the reply is easy to link
// back to the draft. The inbound parser tolerates surrounding text as long as
// exactly one token is present.
func controlReplySubject(action, token, draftSubject string) string {
	subject := fmt.Sprintf("[GH-%s:%s]", action, token)
	if draftSubject = strings.TrimSpace(draftSubject); draftSubject != "" {
		subject += " " + draftSubject
	}
	return subject
}

// mailtoControl builds a mailto: URL that opens a new mail to the inbox with
// the control subject/body pre-filled. Nothing happens until the user sends it.
func mailtoControl(inboxAddress, action, token, draftSubject string) string {
	q := url.Values{}
	q.Set("subject", controlReplySubject(action, token, draftSubject))
	q.Set("body", controlBody())
	enc := strings.ReplaceAll(q.Encode(), "+", "%20")
	return "mailto:" + inboxAddress + "?" + enc
}

// buildApprovalEmail renders the plain-text and HTML bodies of an approval
// request. Agent/owner-provided draft content is escaped before it is embedded
// in the HTML alternative.
func (s *Service) buildApprovalEmail(d model.Draft, atts []model.DraftAttachment, inbox model.Inbox, token string) (string, string, error) {
	to := strings.Join(d.To, ", ")
	cc := strings.Join(d.CC, ", ")
	from := strings.TrimSpace(d.FromAddress)
	if from == "" {
		from = inbox.Address
	}
	body := strings.TrimSpace(d.Text)
	if body == "" {
		body = strings.TrimSpace(d.HTML)
	}
	var attLines strings.Builder
	for _, a := range atts {
		fmt.Fprintf(&attLines, "- %s (%s)\n", a.Filename, humanBytes(a.Size))
	}

	var text strings.Builder
	text.WriteString("An email draft needs your approval before it is sent.\r\n\r\n")
	text.WriteString(inbox.Address + " has asked you to approve the draft below.\r\n")
	text.WriteString("To approve, reply to this email with \"Approve\" as the first line.")
	text.WriteString(" To reject, reply with anything else.")
	text.WriteString(" If the buttons in this email work, you can use those instead.")
	text.WriteString(" Keep the reference line below in the quoted reply.")
	text.WriteString(" Nothing changes until you send your reply.\r\n\r\n")
	text.WriteString("Reference: " + controlRequestMarker(token) + "\r\n\r\n")
	text.WriteString("Prefer to leave feedback? Add it after the first line, or between the markers below keeping them intact. If you are approving, your feedback is recorded for the agent but does not change the email being sent:\r\n\r\n")
	text.WriteString(controlBody() + "\r\n")
	text.WriteString("--- Draft to send ---\r\n")
	text.WriteString("From: " + from + "\r\n")
	text.WriteString("To: " + to + "\r\n")
	if cc != "" {
		text.WriteString("Cc: " + cc + "\r\n")
	}
	text.WriteString("Subject: " + d.Subject + "\r\n\r\n")
	text.WriteString(body + "\r\n")
	if attLines.Len() > 0 {
		text.WriteString("\r\nAttachments:\r\n" + attLines.String())
	}

	approveURL := mailtoControl(inbox.Address, controlApprove, token, d.Subject)
	rejectURL := mailtoControl(inbox.Address, controlReject, token, d.Subject)
	var h strings.Builder
	h.WriteString("<p>An email draft needs your approval before it is sent.</p>")
	h.WriteString("<p><strong>" + html.EscapeString(inbox.Address) + "</strong> has asked you to approve the draft below. ")
	h.WriteString("Choose an action, then <strong>send the email your client opens</strong>. Nothing changes until you send it.</p>")
	h.WriteString(`<p><a href="` + html.EscapeString(approveURL) + `" style="display:inline-block;padding:10px 16px;background:#1f6feb;color:#fff;text-decoration:none;border-radius:6px;margin-right:8px">Approve &amp; Send</a>`)
	h.WriteString(`<a href="` + html.EscapeString(rejectURL) + `" style="display:inline-block;padding:10px 16px;background:#b42318;color:#fff;text-decoration:none;border-radius:6px">Reject</a></p>`)
	h.WriteString("<p>If the buttons don't open your mail app, <strong>reply to this email</strong> with <strong>Approve</strong> as the first line to approve, or <strong>anything else</strong> to reject. Keep the reference line below in the quoted reply.</p>")
	h.WriteString("<p>Reference: " + html.EscapeString(controlRequestMarker(token)) + "</p>")
	h.WriteString("<p>You may add feedback after the first line, or between the markers in the message body, keeping the markers intact. If you are approving, your feedback is recorded for the agent but does not change the email being sent.</p>")
	h.WriteString("<hr><h3>Draft to send</h3>")
	h.WriteString("<p><strong>From:</strong> " + html.EscapeString(from) + "<br>")
	h.WriteString("<strong>To:</strong> " + html.EscapeString(to) + "<br>")
	if cc != "" {
		h.WriteString("<strong>Cc:</strong> " + html.EscapeString(cc) + "<br>")
	}
	h.WriteString("<strong>Subject:</strong> " + html.EscapeString(d.Subject) + "</p>")
	h.WriteString("<pre style=\"white-space:pre-wrap;font-family:inherit\">" + html.EscapeString(body) + "</pre>")
	if len(atts) > 0 {
		h.WriteString("<p><strong>Attachments:</strong></p><ul>")
		for _, a := range atts {
			h.WriteString("<li>" + html.EscapeString(a.Filename) + " (" + humanBytes(a.Size) + ")</li>")
		}
		h.WriteString("</ul>")
	}
	return text.String(), h.String(), nil
}

// buildApprovalMessage renders the full MIME message, attaching the draft's
// attachment bytes so the approver reviews exactly what will be sent.
func (s *Service) buildApprovalMessage(inbox model.Inbox, to []string, d model.Draft, msgID, text, html string, atts []model.DraftAttachment) ([]byte, []transport.OutboundAttachment, error) {
	attachments := make([]transport.OutboundAttachment, 0, len(atts))
	parts := make([]mailparse.Attachment, 0, len(atts))
	for i, a := range atts {
		data, err := os.ReadFile(filepath.Join(s.Config.DataDir, filepath.FromSlash(a.RawPath)))
		if err != nil {
			return nil, nil, err
		}
		contentType := strings.TrimSpace(a.ContentType)
		if contentType == "" {
			contentType = "application/octet-stream"
		}
		filename := mailparse.SafeAttachmentFilename(a.Filename, i+1, contentType)
		attachments = append(attachments, transport.OutboundAttachment{Filename: filename, ContentType: contentType, Content: data})
		parts = append(parts, mailparse.Attachment{Filename: filename, ContentType: contentType, Content: data})
	}
	raw, err := mailparse.BuildMessage(mailparse.Address{Name: inbox.DisplayName, Address: inbox.Address}, to, nil, nil, approvalEmailSubject(d.Subject), text, html, msgID, "", nil, time.Now().UTC(), parts)
	if err != nil {
		return nil, nil, err
	}
	return raw, attachments, nil
}

func humanBytes(n int64) string {
	const unit = 1024
	if n < unit {
		return fmt.Sprintf("%d B", n)
	}
	div, exp := int64(unit), 0
	for m := n / unit; m >= unit; m /= unit {
		div *= unit
		exp++
	}
	return fmt.Sprintf("%.1f %cB", float64(n)/float64(div), "KMGTPE"[exp])
}
